In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\choiy\Desktop\aegis_prac\data\training\p000001.psv', sep='|')
df

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,1,0
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,2,0
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,3,0
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,4,0
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,5,0
5,110.0,91.0,NaN,NaN,NaN,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,6,0
6,108.0,92.0,36.11,123.0,77.00,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,7,0
7,106.0,90.5,NaN,93.0,76.33,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,8,0
8,104.0,95.0,NaN,133.0,88.33,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,9,0
9,102.0,91.0,NaN,134.0,87.33,NaN,30.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,10,0
10,104.0,92.0,37.17,138.0,86.67,NaN,19.0,NaN,23.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,11,0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,12,0
12,102.0,93.0,NaN,129.0,77.00,NaN,24.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,13,0
13,108.0,90.0,NaN,122.0,96.67,NaN,27.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,14,0
14,106.0,90.0,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,15,0
15,109.0,91.0,36.56,132.0,96.67,NaN,24.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,16,0
16,103.0,90.0,NaN,NaN,NaN,NaN,30.0,NaN,21.0,45.0,...,5.7,NaN,317.0,83.14,0,NaN,NaN,-0.03,17,0
17,104.0,92.0,NaN,132.0,81.33,NaN,28.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,18,0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,19,0
19,109.0,91.0,37.11,147.0,91.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,20,0
20,113.0,90.0,NaN,NaN,NaN,NaN,17.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,21,0
21,98.0,93.0,NaN,134.0,83.33,NaN,28.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,22,0
22,100.0,85.0,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,23,0
23,102.0,89.0,36.67,132.0,94.00,NaN,32.0,NaN,20.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,24,0
24,108.0,87.0,NaN,149.0,89.67,NaN,30.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,25,0
25,107.0,90.0,NaN,156.0,96.67,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,26,0
26,104.0,91.0,NaN,168.0,141.33,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,27,0
27,102.0,88.0,36.50,146.0,90.67,NaN,27.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,28,0
28,106.0,91.0,NaN,137.0,75.67,NaN,25.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,29,0
29,112.0,89.0,NaN,157.0,123.67,NaN,20.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,30,0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,31,0
31,107.0,91.0,37.44,141.0,97.00,NaN,24.5,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,32,0
32,111.0,NaN,NaN,138.0,126.00,NaN,31.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,33,0
33,104.0,90.0,NaN,126.0,117.33,NaN,27.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,34,0
34,102.0,NaN,NaN,103.0,75.67,NaN,24.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,35,0
35,99.0,89.0,37.11,113.0,96.33,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,36,0
36,97.0,89.0,NaN,110.0,72.00,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,37,0
37,110.0,89.0,NaN,108.0,90.67,NaN,24.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,38,0
38,108.0,89.0,NaN,139.0,102.33,NaN,26.0,NaN,20.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,39,0
39,117.0,NaN,36.78,126.0,104.67,NaN,22.0,NaN,NaN,48.0,...,14.7,NaN,338.0,83.14,0,NaN,NaN,-0.03,40,0
40,107.0,93.0,NaN,NaN,NaN,NaN,21.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,41,0
41,117.0,NaN,36.33,126.0,84.00,NaN,25.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,42,0
42,NaN,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,43,0
43,114.5,89.5,NaN,157.5,121.17,NaN,26.0,NaN,18.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,44,0
44,96.0,95.0,NaN,119.5,87.50,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,45,0
45,84.0,95.0,NaN,111.5,67.83,NaN,21.5,NaN,19.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,46,0
46,86.0,97.0,NaN,127.0,76.33,NaN,18.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,47,0
47,99.5,96.0,NaN,143.5,96.17,NaN,21.5,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,48,0
48,100.0,86.5,NaN,181.0,104.00,NaN,30.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,49,0
49,76.0,NaN,NaN,85.0,53.00,NaN,17.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,50,0
50,81.0,99.0,NaN,99.0,51.00,NaN,17.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,51,0
51,85.0,100.0,NaN,103.0,48.00,NaN,26.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,52,0
52,86.0,93.0,NaN,87.0,44.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,53,0
53,84.0,85.0,NaN,78.0,44.00,NaN,18.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,54,0

In [3]:
print(df.shape)
print(df.columns.tolist())
df.head()

(54, 41)
['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp', 'EtCO2', 'BaseExcess', 'HCO3', 'FiO2', 'pH', 'PaCO2', 'SaO2', 'AST', 'BUN', 'Alkalinephos', 'Calcium', 'Chloride', 'Creatinine', 'Bilirubin_direct', 'Glucose', 'Lactate', 'Magnesium', 'Phosphate', 'Potassium', 'Bilirubin_total', 'TroponinI', 'Hct', 'Hgb', 'PTT', 'WBC', 'Fibrinogen', 'Platelets', 'Age', 'Gender', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS', 'SepsisLabel']

,HR,O2Sat,Temp,SBP,MAP,DBP,Resp,EtCO2,BaseExcess,HCO3,...,WBC,Fibrinogen,Platelets,Age,Gender,Unit1,Unit2,HospAdmTime,ICULOS,SepsisLabel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,1,0
1,97.0,95.0,NaN,98.0,75.33,NaN,19.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,2,0
2,89.0,99.0,NaN,122.0,86.00,NaN,22.0,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,3,0
3,90.0,95.0,NaN,NaN,NaN,NaN,30.0,NaN,24.0,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,4,0
4,103.0,88.5,NaN,122.0,91.33,NaN,24.5,NaN,NaN,NaN,...,NaN,NaN,NaN,83.14,0,NaN,NaN,-0.03,5,0

In [ ]:
import os
files = os.listdir(r'C:\Users\choiy\Desktop\aegis_prac\data\training')
print(f"전체 환자 수: {len(files)}")

전체 환자 수: 20336

In [6]:
import glob
all_files = glob.glob(r"C:\Users\choiy\Desktop\aegis_prac\data\training\*.psv")

sepesis_count = 0
for f in all_files:
    df_temp = pd.read_csv(f, sep='|')
    if df_temp['SepsisLabel'].max() == 1:
        sepesis_count += 1

print(f"패혈증 환자 수 : {sepesis_count}")
print(f"정상 환자 수 : {len(all_files) - sepesis_count}")
print(f"패혈증 비율 : {sepesis_count/len(all_files)*100:.1f}%")

패혈증 환자 수 : 1790
정상 환자 수 : 18546
패혈증 비율 : 8.8%

In [12]:
import sys

sys.path.append(r'C:\Users\choiy\Desktop\aegis_prac')

from config import *
import duckdb

with duckdb.connect(DB_PATH) as conn:
    conn.execute("""
        CREATE TABLE IF NOT EXISTS patients AS
        SELECT * FROM read_csv_auto(
            'data/training/*.psv',
            delim='|',
            header=true,
            filename=true
        )
    """)
    print(conn.execute("SELECT COUNT(*) FROM patients").fetchone()[0])

790215

In [24]:
import pandas as pd

conn = duckdb.connect(DB_PATH)

pd.set_option('display.max_columns', None)  # 모든 컬럼 표시
pd.set_option('display.max_rows', None)     # 모든 행 표시
pd.set_option('display.width', None)        # 너비 제한 없음

In [ ]:
df = conn.execute("SELECT HR, Temp, Lactate FROM patients LIMIT 10").df()
print(df)
print(df.dtypes)

      HR   Temp  Lactate
0    NaN    NaN      NaN
1   97.0    NaN      NaN
2   89.0    NaN      NaN
3   90.0    NaN      NaN
4  103.0    NaN      NaN
5  110.0    NaN      NaN
6  108.0  36.11      NaN
7  106.0    NaN      NaN
8  104.0    NaN      NaN
9  102.0    NaN      NaN
HR         float64
Temp       float64
Lactate    float64
dtype: object

In [ ]:
columns = ['HR','O2Sat','Temp','SBP','MAP','DBP','Resp',
            'BaseExcess','HCO3','FiO2','pH','PaCO2','SaO2','AST',
            'BUN','Alkalinephos','Calcium','Chloride','Creatinine',
            'Bilirubin_direct','Glucose','Lactate','Magnesium',
            'Phosphate','Potassium','Bilirubin_total','TroponinI',
            'Hct','Hgb','PTT','WBC','Fibrinogen','Platelets']

query = "SELECT " + ",\n".join([
    f"ROUND(100.0 * SUM(CASE WHEN {c} IS NULL OR isnan({c}) THEN 1 ELSE 0 END) / COUNT(*), 1) AS {c}"
    for c in columns
]) + " FROM patients"

df = conn.execute(query).df()
print(df.T.sort_values(0))  # .T하면 컬럼이 0이 됨.

                     0
HR                 7.7
Resp               9.8
MAP               10.2
O2Sat             12.0
SBP               15.2
DBP               48.1
Temp              66.2
FiO2              85.8
Glucose           87.8
Hct               88.2
pH                88.5
Potassium         89.1
BaseExcess        89.6
Hgb               91.2
PaCO2             91.2
Chloride          91.7
BUN               91.8
HCO3              91.9
Magnesium         92.2
WBC               92.5
Creatinine        93.4
Platelets         93.5
SaO2              95.0
Calcium           95.0
Phosphate         95.0
PTT               95.2
Lactate           96.6
Alkalinephos      98.5
AST               98.5
Bilirubin_total   98.8
Fibrinogen        99.2
Bilirubin_direct  99.9
TroponinI         99.9

In [ ]:
# 모델링할 때 그냥 안 쓰기
# 원본 데이터는 건드리지 않고 제외만 하기
# Hgb, PaCO2, Chloride, BUN, HCO3, Magnesium, WBC, Creatinine, Platelets, SaO2              
# Calcium           
# ...
# Bilirubin_total   
# Fibrinogen       
# Bilirubin_direct  
# TroponinI